export const WINDOWS = {
    'Finder': 1,
    "Activity Monitor": 2,
    "App Store": 3,
    "Books": 4,
    "Calculator": 5,
    "Discord": 6,
    "Facebook": 7,
    "Github": 8,
    "Google Chrome": 9,
    "Instagram": 10,
    "Notes": 11,
    "Photos": 12,
    "Qr Encoder": 13,
    "Launchpad": 14,
    "Safari": 15,
    "Settings": 16,
    "Spotify": 17,
    "Telegram": 18,
    "Terminal": 19,
    "Twitter": 21,
    "Whatsapp": 22,
    "Xcode": 23,
    "Youtube": 24,
    'Trash': 25
}
